In [1]:
import pandas as pd
import numpy as np
from scipy.stats import trim_mean
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

In [2]:
DATA = Path('..') / 'data'

In [5]:
state = pd.read_csv(DATA / "state.csv")
state.head(8)

         State  Population  Murder.Rate Abbreviation
0      Alabama     4779736          5.7           AL
1       Alaska      710231          5.6           AK
2      Arizona     6392017          4.7           AZ
3     Arkansas     2915918          5.6           AR
4   California    37253956          4.4           CA
5     Colorado     5029196          2.8           CO
6  Connecticut     3574097          2.4           CT
7     Delaware      897934          5.8           DE

In [26]:
print(int(state.Population.mean()))
print(trim_mean(state.Population, 0.1))
print(state.Population.median())

6162876
4783697.125
4436369.5

In [11]:
percentages = [0.05, 0.25, 0.5, 0.75, 0.95]
df = pd.DataFrame(state['Murder.Rate'].quantile(percentages))
df.index = [f'{p*100}%' for p in percentages]

In [12]:
df.T

             5.0%  25.0%  50.0%  75.0%  95.0%
Murder.Rate   1.6  2.425    4.0   5.55   6.51

In [3]:
df = pd.read_csv(DATA / 'uppsala_companies.csv')
print(df.shape)
print('-'*50)
print(df.info())
print('-'*50)
print(df.dtypes)

(226, 10)
--------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 226 entries, 0 to 225
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   company_id         226 non-null    str
 1   name               226 non-null    str
 2   industry           226 non-null    str
 3   hq_city            226 non-null    str
 4   founded_year       215 non-null    float64
 5   employees          226 non-null    int64
 6   revenue_msek       206 non-null    float64
 7   rd_investment_pct  226 non-null    float64
 8   energy_source      44 non-null     str
 9   last_audit_date    226 non-null    str
dtypes: float64(3), int64(1), str(6)
memory usage: 17.8 KB
None
--------------------------------------------------
company_id               str
name                     str
industry                 str
hq_city                  str
founded_year         float64
employees              int64
revenue_msek         float64
rd_investment_pct    float64
energy_source            str
last_audit_date          str
dtype: object

In [4]:
df.head()

,company_id,name,industry,hq_city,founded_year,employees,revenue_msek,rd_investment_pct,energy_source,last_audit_date
0,C0098,Company_098,Life Science,Stockholm,1993.0,42,81.44,12.42,NaN,2019-08-17
1,C0046,Company_046,Energy,uppsala,1976.0,39,47.70,2.95,District heating,2019-05-23
2,C0099,Company_099,Energy,Gavle,2002.0,42,NaN,0.19,Solar,2023-09-08
3,C0022,Company_022,Other Tech,Uppsala,2005.0,15,13.33,0.83,NaN,2023-06-01
4,C0078,Company_078,Public Health,Uppsala,2007.0,43,48.71,3.63,NaN,2023-07-04

In [5]:
df.isna().sum()

company_id             0
name                   0
industry               0
hq_city                0
founded_year          11
employees              0
revenue_msek          20
rd_investment_pct      0
energy_source        182
last_audit_date        0
dtype: int64

In [6]:
df.hq_city.value_counts()

hq_city
Uppsala       79
Stockholm     43
Vasteras      28
uppsala       20
Norrkoping    19
UPPSALA       13
Gavle         12
 Uppsala       7
stockholm      5
Name: count, dtype: int64

In [7]:
word = ' a sd '
word.replace(' ','').title()

'Asd'

In [8]:
df['hq_city_clean'] = df.hq_city.str.replace(' ','').str.title()
#df['hq_city_clean'] = df['hq_city'].apply(lambda x: x.replace(' ','').title())

In [9]:
df.hq_city_clean.value_counts()

hq_city_clean
Uppsala       119
Stockholm      48
Vasteras       28
Norrkoping     19
Gavle          12
Name: count, dtype: int64

In [10]:
df[df.duplicated()]
#df.duplicated().sum()

,company_id,name,industry,hq_city,founded_year,employees,revenue_msek,rd_investment_pct,energy_source,last_audit_date,hq_city_clean
35,C0180,Company_180,Energy,Uppsala,2001.0,5,3.73,0.00,District heating,2020-07-27,Uppsala
142,C0102,Company_102,Agro-Forestry,Uppsala,1986.0,161,465.04,0.96,NaN,2019-11-08,Uppsala
150,C0088,Company_088,Life Science,Uppsala,1983.0,73,138.75,7.95,NaN,2020-10-09,Uppsala
162,C0105,Company_105,Other Tech,Gavle,2014.0,96,177.46,1.28,NaN,2024-12-25,Gavle
166,C0091,Company_091,Energy,Uppsala,1989.0,28,46.48,2.55,Biomass,2020-03-23,Uppsala
188,C0034,Company_034,Agro-Forestry,Vasteras,1972.0,16,30.21,3.61,NaN,2019-12-22,Vasteras

In [11]:
# df.duplicated() Detecta las filas repetidas
df_clean = df.drop(df[df.duplicated()].index)

In [12]:
df_clean.shape

(220, 11)

In [13]:
df_clean.isna().sum().sort_values(ascending=False)

energy_source        178
revenue_msek          20
founded_year          11
industry               0
name                   0
company_id             0
hq_city                0
employees              0
rd_investment_pct      0
last_audit_date        0
hq_city_clean          0
dtype: int64

In [14]:
df_clean = df_clean.dropna(subset=['founded_year'])

In [15]:
df_clean.shape

(209, 11)

In [16]:
df_clean['revenue_msek'] = df_clean['revenue_msek'].fillna(df_clean['revenue_msek'].median())

In [17]:
df_clean.revenue_msek.isna().sum()

np.int64(0)

In [18]:
industries_ls = df_clean[(df_clean.industry == 'Life Science') & (df_clean.employees >= 100)][['name', 'employees', 'revenue_msek']]

industries_ls

            name  employees  revenue_msek
45   Company_094        119        191.13
80   Company_125        134        207.33
111  Company_148        114        265.27
132  Company_169        127         96.30
141  Company_107        163        485.08
144  Company_016        344        994.87
158  Company_217        138        317.99
171  Company_215        648         46.43

In [19]:
industries_ls.shape[0]

8

In [20]:
df_clean['revenue_per_employee'] = df_clean.revenue_msek/df_clean.employees
df_clean.revenue_per_employee

0      1.939048
1      1.223077
2      1.105476
3      0.888667
4      1.132791
         ...
221    1.090000
222    1.709091
223    1.170000
224    1.843023
225    1.852619
Name: revenue_per_employee, Length: 209, dtype: float64

In [21]:
df_clean['size_category'] = df_clean.employees.apply(lambda x: 'small' if x < 50 else ('medium' if 50 <= x <= 500 else 'large'))

df_clean.size_category.value_counts()

size_category
small     148
medium     59
large       2
Name: count, dtype: int64

In [22]:
df_clean.head(2)

,company_id,name,industry,hq_city,founded_year,employees,revenue_msek,rd_investment_pct,energy_source,last_audit_date,hq_city_clean,revenue_per_employee,size_category
0,C0098,Company_098,Life Science,Stockholm,1993.0,42,81.44,12.42,NaN,2019-08-17,Stockholm,1.939048,small
1,C0046,Company_046,Energy,uppsala,1976.0,39,47.70,2.95,District heating,2019-05-23,Uppsala,1.223077,small

In [23]:
df_clean.groupby(by='industry').size()

industry
Agro-Forestry    21
Energy           41
Life Science     73
Other Tech       38
Public Health    36
dtype: int64

In [24]:
df_clean.groupby(by='industry').employees.mean()

industry
Agro-Forestry    39.619048
Energy           64.414634
Life Science     51.356164
Other Tech       55.815789
Public Health    36.777778
Name: employees, dtype: float64

In [25]:
df_clean.groupby(by='industry').revenue_msek.sum().sort_values()

industry
Agro-Forestry    1734.43
Public Health    1951.69
Other Tech       3259.92
Energy           3859.55
Life Science     5656.16
Name: revenue_msek, dtype: float64

In [44]:
summary = df_clean.groupby("industry").agg(
    n_companies=("company_id", "count"),
    avg_employees=("employees", "mean"),
    total_revenue=("revenue_msek", "sum"),
).sort_values("total_revenue", ascending=False)
summary

               n_companies  avg_employees  total_revenue
industry
Life Science            73      51.356164        5656.16
Energy                  41      64.414634        3859.55
Other Tech              38      55.815789        3259.92
Public Health           36      36.777778        1951.69
Agro-Forestry           21      39.619048        1734.43

In [ ]:
#df_clean.groupby(by='industry').agg({'employees': 'mean', })

In [26]:
df_clean.pivot_table(index='industry', columns='size_category', values='company_id', aggfunc='count')

size_category  large  medium  small
industry
Agro-Forestry    NaN     4.0   17.0
Energy           1.0    11.0   29.0
Life Science     1.0    20.0   52.0
Other Tech       NaN    16.0   22.0
Public Health    NaN     8.0   28.0

In [31]:
df_clean.sort_values(by='rd_investment_pct',ascending=False).head(5)

,company_id,name,industry,hq_city,founded_year,employees,revenue_msek,rd_investment_pct,energy_source,last_audit_date,hq_city_clean,revenue_per_employee,size_category
146,C0162,Company_162,Life Science,Vasteras,2012.0,31,46.08,19.66,NaN,2022-05-07,Vasteras,1.486452,small
158,C0217,Company_217,Life Science,Norrkoping,1993.0,138,317.99,19.25,NaN,2022-12-10,Norrkoping,2.304275,medium
57,C0171,Company_171,Life Science,uppsala,1991.0,19,44.45,15.61,NaN,2019-01-18,Uppsala,2.339474,small
58,C0134,Company_134,Life Science,Uppsala,1977.0,10,21.81,15.44,NaN,2022-08-27,Uppsala,2.181000,small
202,C0075,Company_075,Life Science,Uppsala,2002.0,10,11.33,15.19,NaN,2024-10-27,Uppsala,1.133000,small

In [32]:
df_clean.sort_values(by='employees').head(5)

,company_id,name,industry,hq_city,founded_year,employees,revenue_msek,rd_investment_pct,energy_source,last_audit_date,hq_city_clean,revenue_per_employee,size_category
13,C0165,Company_165,Public Health,Stockholm,1997.0,2,1.48,7.52,NaN,2024-05-23,Stockholm,0.740,small
24,C0115,Company_115,Public Health,Uppsala,1996.0,2,1.66,10.76,NaN,2021-03-05,Uppsala,0.830,small
83,C0153,Company_153,Agro-Forestry,Uppsala,1971.0,2,6.52,5.16,NaN,2024-09-01,Uppsala,3.260,small
153,C0073,Company_073,Public Health,Norrkoping,1998.0,2,3.82,9.13,NaN,2020-06-02,Norrkoping,1.910,small
204,C0172,Company_172,Life Science,Gavle,1970.0,2,2.29,8.51,NaN,2024-10-09,Gavle,1.145,small

In [34]:
df_clean['last_audit_date'] = pd.to_datetime(df_clean['last_audit_date'], format='%Y-%m-%d')

In [38]:
df_clean.last_audit_date

0     2019-08-17
1     2019-05-23
2     2023-09-08
3     2023-06-01
4     2023-07-04
         ...
221   2023-05-03
222   2024-09-06
223   2023-11-25
224   2024-04-18
225   2020-11-21
Name: last_audit_date, Length: 209, dtype: datetime64[us]

In [41]:
df_clean['audit_year'] = df_clean.last_audit_date.dt.year
df_clean[['audit_year']]

     audit_year
0          2019
1          2019
2          2023
3          2023
4          2023
..          ...
221        2023
222        2024
223        2023
224        2024
225        2020

[209 rows x 1 columns]

In [43]:
df_clean.audit_year.value_counts().sort_index()

audit_year
2019    33
2020    42
2021    35
2022    29
2023    28
2024    42
Name: count, dtype: int64

---